### Autor: Lazaro Camsca Edson
### Curso: Análisis Numeérico

# Pregunta 1

In [1]:
import __metodos_Iterativos as mi
import numpy as np

toolNick se ha importado correctamente.
__metodos_Iterativos se ha importado correctamente.


In [2]:
# Definimos los valores

A = np.array([[5,2],[1,-4]])
b = np.array([1,0])
x_0 = np.array([1,2])

### Metodo Jacobi

In [3]:
#Realizamos 4 iteraciones
x = mi.Jacobi(A,b,x_0, n_iter=4,v='True')

D: 
 [[ 5  0]
 [ 0 -4]]
E: 
 [[ 0  0]
 [-1  0]]
F: 
 [[ 0 -2]
 [ 0  0]]
========== Invirtiendo matriz D: =============
J:
[[ 2.22044605e-16 -4.00000000e-01]
 [ 2.50000000e-01  0.00000000e+00]]
c:
[0.2 0. ]

========== Iterando la solucion =============

Iteration 0:x = [1 2]
Iteration 1:x = [-0.6   0.25]
Iteration 2:x = [ 0.1  -0.15]
Iteration 3:x = [0.26  0.025]


### Metodo Gauss Seidel

In [4]:
x = mi.Gauss_Seidel(A,b,x_0,n_iter=4,v='True')

D: 
 [[ 5  0]
 [ 0 -4]]
E: 
 [[ 0  0]
 [-1  0]]
F: 
 [[ 0 -2]
 [ 0  0]]
========== Invirtiendo matriz (D-E): =============
G:
[[ 0.  -0.4]
 [ 0.  -0.1]]
c:
[0.2  0.05]
Iteration 0:x = [1 2]
Iteration 1:x = [-0.6  -0.15]
Iteration 2:x = [0.26  0.065]
Iteration 3:x = [0.174  0.0435]


# Pregunta 2
#### Matrices son diagonal dominante

In [5]:
import toolNick as tn
import numpy as np

In [6]:
A = np.array([[4,1],[3,8]])
bo = tn.matrix_Diagonal_Dominante(A)
bo

True

In [13]:
A = np.array([[4,4],[3,8]])
bo = tn.matrix_Diagonal_Dominante(A)
bo

True

In [11]:
A = np.array([[4,1,1],[2,8,-3],[3,2,9]])
bo = tn.matrix_Diagonal_Dominante(A)
bo

True

In [12]:
A = np.array([[4,1,1],[2,8,-7],[3,-10,20]])
bo = tn.matrix_Diagonal_Dominante(A)
bo

False

## Método de Continuación u Homotopía

Para el siguiente método importamos la libreria homotopia.


In [7]:
import numpy as np
from homotopia import *

Se a importado correctamente la libreria homotopia


# Pregunta 5

Sea el sistema no lineal de ecuaciones siguiente:

$f_1(x_1; x_2; x_3) = {x_1}^2 + x_2 − 37 = 0$

$f_2(x_1; x_2; x_3) = x_1 − {x_2}^2 − 5 = 0$

$f_3(x_1; x_2; x_3) = x_3 + x_1 + x_2 − 3 = 0$

Mediante el método de Continuación u Homotopía calcúlese la aproximación de la solución, comenzando en el punto inicial

$P_0 = {({x_1}^{(0)} ; {x_2}^{(0)}  ; {x_3}^{(0)})}^T = {(0; 0; 0)}^T$ y realizando $n = 2$ iteraciones.


In [8]:
F = lambda X : np.array([
                    X[0]**2 * X[1] - 37 ,
                    X[0] - X[1]**2 - 5 ,
                    X[2] + X[0] + X[1] - 3])

J = lambda X : np.array([
                    [ 2*X[0],     1   , 0],
                    [ 1     , -2*X[1] , 0],
                    [ 1     ,    1    , 1]])

X_0 = np.array([0.0, 0.0, 0.0])

x = solve_Homotopia(F, J, X_0, v=True, iv=True)

Hallando X_1:
Hallando k_1:
w_1 = [0. 0. 0.]

J(w_1) :
[[ 0.  1.  0.]
 [ 1. -0.  0.]
 [ 1.  1.  1.]]

Inversa(J(w_1)):
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [-1. -1.  1.]]

k_1 = [  1.66666667  12.33333333 -13.        ]
-------------------------------------------
Hallando k_2:
w_2 = [ 0.83333333  6.16666667 -6.5       ]

J(w_2) :
[[  1.66666667   1.           0.        ]
 [  1.         -12.33333333   0.        ]
 [  1.           1.           1.        ]]

Inversa(J(w_2)):
[[ 0.57216495  0.04639175  0.        ]
 [ 0.04639175 -0.07731959 -0.        ]
 [-0.6185567   0.03092784  1.        ]]

k_2 = [ 7.13402062  0.44329897 -6.57731959]
-------------------------------------------
Hallando k_3:
w_3 = [ 3.56701031  0.22164948 -3.28865979]

J(w_3) :
[[ 7.13402062  1.          0.        ]
 [ 1.         -0.44329897  0.        ]
 [ 1.          1.          1.        ]]

Inversa(J(w_3)):
[[ 0.10649815  0.24024001  0.        ]
 [ 0.24024001 -1.71387719  0.        ]
 [-0.34673816  1.47363718  1.        ]]



# Pregunta 6

Sea el sistema de ecuaciones no lineales siguiente.

$f_1(x_1; x_2) = sin(4πx_1x_2) − 2x_2 − x_1 = 0$

$f_2(x_1; x_2) = {(4π − 1)(e^{2x_1} − e)}/{4π} + 4e{x_2}^2 − 2ex_1 = 0$

Mediante el método de Continuación u Homotopía calcúlese la aproximación de la solución, comenzando en el punto inicial

$P_0 = {({x_1}^{(0)} ; {x_2}^{(0)}  ; {x_3}^{(0)})}^T = {(0; 0; 0)}^T$ y realizando $n = 2$ iteraciones.

In [9]:
F = lambda X : np.array([
                    np.sin(4*np.pi*X[0]*X[1])-2*X[1]-X[0],
                    ((4*np.pi - 1)*(np.e**(2*X[0])-np.e))/(4*np.pi) - 4*np.e*X[1]**2 - 2*np.e*X[0]])

J = lambda X : np.array([
                    [ np.cos(4*np.pi*X[0]*X[1])*(4*np.pi*X[1])-1, np.cos(4*np.pi*X[0]*X[1])*(4*np.pi*X[0])-2  ],
                    [ (4*np.pi - 1)*(2*np.e**(2*X[0]))/(4*np.pi) - 2*np.e, 8*np.e*X[1] ] ])

X_0 = np.array([0.0, 0.0])

x = solve_Homotopia(F, J, X_0, v=True, iv=True)

Hallando X_1:
Hallando k_1:
w_1 = [0. 0.]

J(w_1) :
[[-1.        -2.       ]
 [-3.5957186  0.       ]]

Inversa(J(w_1)):
[[-0.         -0.27810853]
 [-0.5         0.13905426]]

k_1 = [-0.21992062  0.10996031]
-------------------------------------------
Hallando k_2:
w_2 = [-0.10996031  0.05498015]

J(w_2) :
[[-0.31109188 -3.37781623]
 [-3.95913362  1.19561243]]

Inversa(J(w_2)):
[[-0.08698418 -0.24574567]
 [-0.28803815  0.02263281]]

k_2 = [-0.19432895  0.01789741]
-------------------------------------------
Hallando k_3:
w_3 = [-0.09716448  0.0089487 ]

J(w_3) :
[[-0.88755397 -3.22093193]
 [-3.92083576  0.19460081]]

Inversa(J(w_3)):
[[-0.01520145 -0.25160653]
 [-0.30628027  0.06933223]]

k_3 = [-0.19896357  0.05482603]
-------------------------------------------
Hallando k_4:
w_4 = [-0.19896357  0.05482603]

J(w_4) :
[[-0.31749871 -4.47679608]
 [-4.20004783  1.19226076]]

Inversa(J(w_4)):
[[-0.06215746 -0.23339379]
 [-0.21896577  0.01655251]]

k_4 = [-0.18456143  0.01308927]
--------